repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v2.0.4
    hooks:
      - id: dbt-parse
        name: dbt parse
        entry: dbt parse --project-dir ./dbt
      - id: dbt-docs-generate
        name: dbt docs generate
        entry: dbt docs generate --no-compile --project-dir ./dbt
        language: system
      - id: check-script-semicolon
        entry: dbt ls --project-dir ./dbt | grep -v '^#'
      - id: check-script-has-no-table-name
        entry: dbt ls --project-dir ./dbt | grep -v '^#'
      - id: check-model-has-all-columns
        name: Check columns - gold
        files: ^models/gold
      - id: check-model-has-all-columns
        name: Check columns - marts
        files: ^models/marts
      - id: check-model-columns-have-desc
        files: ^models/mart
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.2.4
    hooks:
      - id: sqlfluff-lint
        # For dbt projects, this installs the dbt "extras".
        # You will need to select the relevant dbt adapter for your dialect
        # (https://docs.getdbt.com/docs/available-adapters):
        additional_dependencies: ['dbt-snowflake', 'sqlfluff-templater-dbt']
      - id: sqlfluff-fix
        # Arbitrary arguments to show an example
        args: [--rules, "LT02,CP02"]
        additional_dependencies: ['dbt-snowflake', 'sqlfluff-templater-dbt']
  - repo: https://github.com/tconbeer/sqlfmt
    rev: v0.23.2
    hooks:
      - id: sqlfmt
        language_version: python
        additional_dependencies: [".[jinjafmt]"]
