version: 2

models:
  - name: stg_customers
    description: Raw customers table
  - name: stg_projects
    description: Raw projects table

  - name: tfm_customers_engagements
    description: Transformed customers engagements table

  - name: tfm_customers_info
    description: Transformed customers table
    columns:
      - name: project_id
        description: Unique identifier for a project
        data_type: string
        data_tests:
          - not_null
          - dbt_utils.not_empty_string

  - name: tfm_customers
    description: Transformed customers table

  - name: tfm_projects
    description: Transformed projects table

  - name: dw_customers_project
    description: Data warehouse customers table

  - name: mrt_customer
    description: Mart customers table

  - name: mrt_project
    description: Mart projects table
