version: 2

sources:
  - name: SUPERSIDE
    schema: PUBLIC
    tables:
      - name: PROJECT
        identifier: DIM_PROJECT_SOURCE

      - name: CUSTOMERS
        identifier: CSV_SOURCE
        loaded_at_field: _airbyte_extracted_at
        freshness:
          warn_after: { count: 7, period: day }
          # error_after: {count: 14, period: day} -- don't know when superside will check my work
