superside:
  outputs:
    dev:
      account: czb09219.us-east-1
      database: SUPERSIDE
      password: hRjRTs^4!J7GE2!
      role: ACCOUNTADMIN
      schema: PUBLIC
      threads: 1
      type: snowflake
      user: lucasudar
      warehouse: COMPUTE_WH
  target: dev